name: update metrics info
on:
  schedule: [{cron: "0 0 * * 1"}]
  push:
      branches:
            - main
  workflow_dispatch:
jobs:
    basic:
        name: Update basic metrics
        runs-on: ubuntu-latest
        permissions:
           contents: write
        steps:
          - name: basic
            if: ${{ success() || failure() }}
            uses: lowlighter/metrics@latest
            with:
              filename: github-basic.svg
              token: ${{ secrets.METRICS_TOKEN }}
              config_timezone: Asia/Shanghai
              base: header, activity, community, repositories, metadata
              base_indepth: yes
              plugin_followup: yes
              plugin_followup_archived: yes
              plugin_followup_sections: repositories
    languages:
        name: Update languages metrics
        runs-on: ubuntu-latest
        permissions:
           contents: write
        steps:
          - name: language
            if: ${{ success() || failure() }}
            uses: lowlighter/metrics@latest
            with:
              filename: github-languages.svg
              token: ${{ secrets.METRICS_TOKEN }}
              config_timezone: Asia/Shanghai
              base: ""
              plugin_introduction: yes
              plugin_introduction_title: yes
              plugin_isocalendar: yes
              plugin_isocalendar_duration: half-year
              plugin_languages: yes
              plugin_languages_analysis_timeout: 15
              plugin_languages_analysis_timeout_repositories: 7.5
              plugin_languages_categories: markup, programming
              plugin_languages_colors: github
              plugin_languages_limit: 8
              plugin_languages_recent_categories: markup, programming
              plugin_languages_recent_days: 14
              plugin_languages_recent_load: 300
              plugin_languages_sections: most-used
              plugin_languages_threshold: 0%
              plugin_lines: yes
              plugin_lines_history_limit: 1
              plugin_lines_repositories_limit: 4
              plugin_lines_sections: base
    activity:
        name: Update activity metrics
        runs-on: ubuntu-latest
        permissions:
           contents: write
        steps:
          - name: activity
            if: ${{ success() || failure() }}
            uses: lowlighter/metrics@latest
            with:
              filename: github-activity.svg
              token: ${{ secrets.METRICS_TOKEN }}
              config_timezone: Asia/Shanghai
              base: ""
              plugin_activity: yes
              plugin_activity_limit: 7
              plugin_activity_days: 14
              plugin_activity_visibility: all
              plugin_activity_timestamps: yes
              plugin_stargazers: yes
              plugin_stargazers_charts_type: graph
    achievements:
        name: Update achievements metrics
        runs-on: ubuntu-latest
        permissions:
           contents: write
        steps:
          - name: achievements
            if: ${{ success() || failure() }}
            uses: lowlighter/metrics@latest
            with:
              filename: github-achievements.svg
              token: ${{ secrets.METRICS_TOKEN }}
              config_timezone: Asia/Shanghai
              base: ""
              plugin_achievements: yes
              plugin_achievements_threshold: C
              plugin_achievements_secrets: yes
              plugin_achievements_display: detailed
              plugin_achievements_limit: 6
